CREATE TABLE account(
    accountID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    first VARCHAR(20) NOT NULL,
    last VARCHAR(50) NOT NULL,
    sid INT UNSIGNED NOT NULL,
    role TINYINT(1) NOT NULL
);